[package]
name = "welch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4.0"
rustfft = "6.0.1"

[dev-dependencies]
complot = "0.3.2"
